name: gnu_pingpong_app
description: "경상대학교 경상탁구가족(경탁가) 동아리의 공식 앱입니다."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  dio: ^5.8.0+1

  shared_preferences: ^2.0.17

  image_picker: ^0.8.7

  provider: ^6.1.1

  path_provider: ^2.1.2

  # 블루투스 기능은 현재 사용하지 않음
  # flutter_bluetooth_serial: ^0.4.0

  device_info_plus: ^10.1.2
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.5
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.0
  mockito: ^5.4.3
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  collection: ^1.18.0 # 기존 의존성 (최신 버전 확인 권장)
  gotrue: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/
    - .env.example
