name: Flutter Web Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 수동으로 워크플로우 실행 가능

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install dependencies
        run: |
          cd flutter-app
          flutter pub get

      - name: Build Web
        run: |
          cd flutter-app
          flutter build web --release --base-href /GNU-PingPong-App/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutter-app/build/web
          force_orphan: true
