name: Flutter CI/CD

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flutter-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"
          cache: true

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.6.1"

      - name: Create .env file
        run: |
          echo "PROD_SUPABASE_URL=${{ secrets.PROD_SUPABASE_URL }}" > .env
          echo "PROD_SUPABASE_ANON_KEY=${{ secrets.PROD_SUPABASE_ANON_KEY }}" >> .env
          echo "TEST_SUPABASE_URL=${{ secrets.TEST_SUPABASE_URL }}" >> .env
          echo "TEST_SUPABASE_ANON_KEY=${{ secrets.TEST_SUPABASE_ANON_KEY }}" >> .env

      - name: Clean packages
        run: |
          flutter clean
          flutter pub cache clean
          
      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none . || echo "Formatting issues found, but continuing build."
        continue-on-error: true

      - name: Analyze project source
        run: flutter analyze || echo "Analysis issues found, but continuing build."
        continue-on-error: true

      - name: Run unit and widget tests
        run: flutter test test/

      - name: Create production .env file for build
        run: |
          echo "PROD_SUPABASE_URL=${{ secrets.PROD_SUPABASE_URL }}" > .env
          echo "PROD_SUPABASE_ANON_KEY=${{ secrets.PROD_SUPABASE_ANON_KEY }}" >> .env

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./flutter-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"
          cache: true

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.6.1"

      - name: Clean packages
        run: |
          flutter clean
          flutter pub cache clean
          
      - name: Install dependencies
        run: flutter pub get

      - name: Create production .env file for build
        run: |
          echo "PROD_SUPABASE_URL=${{ secrets.PROD_SUPABASE_URL }}" > .env
          echo "PROD_SUPABASE_ANON_KEY=${{ secrets.PROD_SUPABASE_ANON_KEY }}" >> .env

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos